select * from customer limit 20

--Q1 what is the total revenue generated by male vs. female customers?
SELECT "Gender",SUM("Purchase Amount (USD)") AS "Revenue"
FROM customer
GROUP BY "Gender"

--Q2 which customers used a discount but still spent more than the average purchase ammount?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes' 
  AND "Purchase Amount (USD)" > (
      SELECT AVG("Purchase Amount (USD)") 
      FROM customer
  );

--Q3 which are the top 5 products with the highest average review rating?
SELECT "Item Purchased", ROUND(AVG("Review Rating")::numeric, 2) AS "Average Product rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;

--Q4 compare the average purchase amounts between standard and express shipping?
SELECT "Shipping Type",
ROUND (AVG ("Purchase Amount (USD)"), 2)
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

--Q5 Do subscribed customers spend more? comprare average spend and total revenue between subscribers and non subscribers?
SELECT "Subscription Status",
COUNT("Customer ID") AS "Total Customers",
ROUND(AVG("Purchase Amount (USD)"), 2) AS "Avg Spend",
ROUND(SUM("Purchase Amount (USD)"), 2) AS "Total Revenue"
FROM customer
GROUP BY "Subscription Status"
ORDER BY "Total Revenue" DESC, "Avg Spend" DESC;

--Q6. Which 5 products have the highest percentage of purchase with discounts applied?
SELECT "Item Purchased",
ROUND (SUM (CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) * 100.0/COUNT(*),2) AS "Discount Rate"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Discount Rate" DESC
LIMIT 5;

--Q7. Segement customers into New, Returning, and loyal based on their total number of previous purchases, and show count of each segment.
WITH "Customer Type" AS (
    SELECT "Customer ID", "Previous Purchases",
    CASE
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS "Customer Segment"
    FROM customer
)
SELECT "Customer Segment", COUNT(*) AS "Number of Customers"
FROM "Customer Type"
GROUP BY "Customer Segment";

--Q8. What are the top 3 most purchased products within each category?
WITH "Item Counts" AS (
    SELECT
        "Category",
        "Item Purchased",
        COUNT("Customer ID") AS "total orders"
    FROM customer
    GROUP BY
        "Category",
        "Item Purchased"
),
"Ranked Items" AS (
    SELECT
        "Category",
        "Item Purchased",
        "total orders",
        ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY "total orders" DESC) AS "Rank"
    FROM "Item Counts"
)
SELECT
    "Category",
    "Item Purchased",
    "total orders"
FROM "Ranked Items"
WHERE "Rank" <= 3;

--Q9. Are Customers who are not buyers (more than 5 previous purchases ) also likely to subscribe?
SELECT "Subscription Status",
COUNT("Customer ID") AS "Repeat Buyers"
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status"

--Q10. What is the revenue contribution of each age group?
ALTER TABLE customer
ADD COLUMN age_group VARCHAR(20);	

INSERT INTO age_group (id, age_group_text, total_num) VALUES
(1, 'Young Adult', NULL),
(2, 'Middle-aged', NULL),
(3, 'Adult', NULL),
(4, 'Senior', NULL);

UPDATE customer
SET age_group = CASE
    WHEN age >= 18 AND age <= 25 THEN 'Young Adult'
    WHEN age > 25 AND age <= 45 THEN 'Middle-age'

    ELSE 'Adult'
END;

SELECT age_group, SUM("Purchase Amount (USD)") AS "Total Revenue"
FROM customer
GROUP BY age_group
ORDER BY "Total Revenue" DESC;


UPDATE customer
SET age_group = CASE
    WHEN "Age" = 18 THEN 'Adult'
    WHEN "Age" >= 18 AND "Age" <= 25 THEN 'Young Adult'
    WHEN "Age" > 25 AND "Age" <= 45 THEN 'Middle-age'
    WHEN "Age" > 45 THEN 'Senior'
    ELSE 'child'
END;

SELECT age_group, SUM("Purchase Amount (USD)") AS "Total Revenue"
FROM customer
GROUP BY age_group
ORDER BY "Total Revenue" DESC;